[package]
name = "ironfoil-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "GUI for ironfoil"
repository.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
eframe = { workspace = true, features = ["default_fonts", "glow", "persistence"] }
egui.workspace = true
egui_extras = { workspace = true, features = ["svg"] }
egui-toast.workspace = true
env_logger.workspace = true
humansize.workspace = true
image.workspace = true
ironfoil-core = { path = "../core", version = "0.4.7" }
log.workspace = true
rfd.workspace = true
serde.workspace = true
strum = { workspace = true, features = ["derive"] }

[build-dependencies]
vergen-gitcl.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { workspace = true, features = ["default_fonts", "glow", "persistence", "wayland", "x11"] }

[lints]
workspace = true
