compile:
	typst c banner-light.typ -f svg
	typst c banner-dark.typ -f svg
	typst c repo_card.typ -f png
	typst c ./download-linux.typ -f svg
	typst c ./download-windows.typ -f svg
	typst c ./download-macos.typ -f svg
