[package]
name = "ironfoil"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Transfer to NS title installers from the command-line"
repository.workspace = true
license.workspace = true

[package.metadata.dist]
dist = false

[dependencies]
clap.workspace = true
color-eyre.workspace = true
env_logger.workspace = true
indicatif.workspace = true
ironfoil-core = { path = "../core", version = "0.4.5" }

[lints]
workspace = true
