[package]
name = "ironfoil-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Core library for ironfoil"
repository.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
log.workspace = true
thiserror.workspace = true
walkdir.workspace = true

# network
percent-encoding = { workspace = true, optional = true }

# usb
crc32c = { workspace = true, optional = true }
nusb = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
rstest.workspace = true

[features]
default = ["network", "rcm", "usb"]
network = ["dep:percent-encoding"]
rcm = ["dep:nusb"]
usb = ["dep:crc32c", "dep:nusb", "dep:serde"]

[lints]
workspace = true
